global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'carbon-capture-backend'
    static_configs:
      - targets: ['backend:3001']
    scrape_interval: 10s
    metrics_path: '/api/v1/metrics'
    params:
      format: ['prometheus']

  - job_name: 'carbon-capture-ai-engine'
    static_configs:
      - targets: ['ai-engine:8000']
    scrape_interval: 30s
    metrics_path: '/metrics'
    params:
      format: ['prometheus']

  - job_name: 'carbon-capture-frontend'
    static_configs:
      - targets: ['frontend:3000']
    scrape_interval: 30s
    metrics_path: '/api/metrics'
    params:
      format: ['prometheus']

  - job_name: 'mongodb'
    static_configs:
      - targets: ['mongodb:27017']
    scrape_interval: 30s

  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']
    scrape_interval: 15s

  - job_name: 'mosquitto'
    static_configs:
      - targets: ['mosquitto:8883']
    scrape_interval: 30s

  # Node exporter for system metrics (if running on host)
  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 15s

  # Cadvisor for container metrics
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
    scrape_interval: 15s
    metrics_path: '/metrics/cadvisor'

# Alerting configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets: ['alertmanager:9093']

# Remote write configuration (optional - for long-term storage)
# remote_write:
#   - url: "https://prometheus-prod-10-prod-us-central-0.grafana.net/api/prom/push"
#     basic_auth:
#       username: "your-username"
#       password: "your-password"
